defmodule Eva.Coding.Diff do
  @moduledoc """
  Line-level diffing for the coding tools. Generated by GLM 5.2

  Produces an ndiff-style diff string together with the 1-indexed line number of
  the first change in the new text, and a unified-diff patch. Backed by
  `List.myers_difference/2`, so the output is a minimal, `git apply`-compatible
  edit script.

  Myers does not produce byte-identical output to Python's `difflib` (which uses
  Ratcliff–Obershelp), but the patches are valid and apply cleanly. Line
  splitting assumes LF terminators; the edit tool normalizes CRLF/CR to LF
  before diffing.

  ## Performance tradeoff

  `List.myers_difference/2` is Myers' O(ND) algorithm: N = total lines, D = edit
  distance (number of changed lines). Two regimes, measured on this
  implementation against a hand-rolled Myers of identical semantics:

    Localized edits (edit_tool's real workload — D stays tiny because oldText
    matching bounds D by the edit size, never the file size):
        50 lines, 1 change      diff ~0.02ms   patch ~0.03ms
        500 lines, 1 change     diff ~0.19ms   patch ~0.3ms
        5000 lines, 1 change    diff ~1.6ms    patch ~2ms
        10000 lines, identical  diff ~2.4ms    patch ~4ms

    Pathological (full rewrite, D ~ N) — quadratic blow-up:
        100 lines               diff ~0.7ms
        300 lines               diff ~7.5ms
        1000 lines              diff ~160ms

  stdlib's Myers is ~3-5x faster than a naive Elixir port on the pathological
  case (better constants), but it is still O(ND) — the cliff is deferred, not
  removed. On the localized-edit regime it is ~1.8x slower than the tuple-indexed
  snake-slide it replaced, which is irrelevant at these absolute times (sub-2ms
  even at 5000 lines, invisible next to an LLM round-trip).

  The quadratic case is unreachable from edit_tool (D is bounded by the edit
  size, not the file size), and write_tool does not diff, so this module is
  safe as used today. If the module ever diffs two unrelated large files, switch
  to Myers' linear-space divide-and-conquer variant (Myers 1986, sec. 4b) —
  O(N) memory at roughly 2x the time — or a Patience/Hunt-Szymanski diff.
  """

  @default_context 3

  @doc """
  Computes `{diff, first_changed_line}`.

  `diff` is an ndiff-style string: unchanged lines are prefixed with `"  "`,
  removed lines with `"- "`, and added lines with `"+ "`, joined with `"\n"`.

  `first_changed_line` is the 1-indexed line number in `new` where the first
  change appears, or `nil` when `old` and `new` are identical. The walk mirrors
  Python's `difflib.ndiff` counting semantics.
  """
  @spec diff_string(String.t(), String.t()) :: {String.t(), non_neg_integer() | nil}
  def diff_string(old, new) do
    a = split_lines(old)
    b = split_lines(new)
    runs = List.myers_difference(a, b)

    diff =
      runs |> Enum.flat_map(&expand_run/1) |> Enum.map(&format_ndiff_line/1) |> Enum.join("\n")

    {diff, first_changed_line(runs)}
  end

  @doc """
  Builds a unified-diff patch for the change from `old` to `new`, using `path`
  as both the "from" and "to" file. Context defaults to #{@default_context}
  lines, matching `difflib.unified_diff`. Returns `""` when the texts are
  identical.
  """
  @spec unified_patch(path :: String.t(), old :: String.t(), new :: String.t()) :: String.t()
  def unified_patch(path, old, new) do
    a = split_keepends(old)
    b = split_keepends(new)
    opcodes = to_opcodes(List.myers_difference(a, b))

    build_unified(path, a, b, opcodes, @default_context)
  end

  ## ndiff formatting + first changed line

  defp expand_run({:eq, lines}), do: Enum.map(lines, &{:eq, &1})
  defp expand_run({:del, lines}), do: Enum.map(lines, &{:del, &1})
  defp expand_run({:ins, lines}), do: Enum.map(lines, &{:ins, &1})

  defp format_ndiff_line({:eq, line}), do: "  " <> line
  defp format_ndiff_line({:del, line}), do: "- " <> line
  defp format_ndiff_line({:ins, line}), do: "+ " <> line

  # Walks the grouped runs tracking the new-text line number, mirroring
  # difflib.ndiff counting: `eq` and `ins` both advance the new line cursor;
  # `del` does not advance it. Returns the 1-indexed first changed new-line
  # number, or nil when the texts are identical.
  defp first_changed_line(runs) do
    Enum.reduce(runs, {0, nil}, fn run, {n, first} ->
      case run do
        {:eq, lines} ->
          {n + length(lines), first}

        {:ins, lines} ->
          n = n + length(lines)
          first = if is_nil(first), do: n - length(lines) + 1, else: first
          {n, first}

        {:del, _lines} ->
          first = if is_nil(first), do: max(n + 1, 1), else: first
          {n, first}
      end
    end)
    |> elem(1)
  end

  ## opcodes from grouped runs (difflib-style: equal/delete/insert/replace)

  defp to_opcodes(runs) do
    {codes_rev, pending, _i, _j} =
      Enum.reduce(runs, {[], nil, 0, 0}, fn run, {codes, pending, i, j} ->
        case {run, pending} do
          {{:eq, lines}, nil} ->
            count = length(lines)
            {codes, {:equal, i, j, count}, i + count, j + count}

          {{:eq, lines}, {:equal, i1, j1, count}} ->
            {codes, {:equal, i1, j1, count + length(lines)}, i + length(lines), j + length(lines)}

          {{:eq, lines}, {:change, i1, j1, dc, ic}} ->
            {[close_change(i1, j1, dc, ic) | codes], {:equal, i, j, length(lines)},
             i + length(lines), j + length(lines)}

          {{:del, lines}, nil} ->
            {codes, {:change, i, j, length(lines), 0}, i + length(lines), j}

          {{:del, lines}, {:change, i1, j1, dc, ic}} ->
            {codes, {:change, i1, j1, dc + length(lines), ic}, i + length(lines), j}

          {{:del, lines}, {:equal, i1, j1, count}} ->
            {[{:equal, i1, i1 + count, j1, j1 + count} | codes],
             {:change, i, j, length(lines), 0}, i + length(lines), j}

          {{:ins, lines}, nil} ->
            {codes, {:change, i, j, 0, length(lines)}, i, j + length(lines)}

          {{:ins, lines}, {:change, i1, j1, dc, ic}} ->
            {codes, {:change, i1, j1, dc, ic + length(lines)}, i, j + length(lines)}

          {{:ins, lines}, {:equal, i1, j1, count}} ->
            {[{:equal, i1, i1 + count, j1, j1 + count} | codes],
             {:change, i, j, 0, length(lines)}, i, j + length(lines)}
        end
      end)

    codes =
      case pending do
        nil -> codes_rev
        {:equal, i1, j1, count} -> [{:equal, i1, i1 + count, j1, j1 + count} | codes_rev]
        {:change, i1, j1, dc, ic} -> [close_change(i1, j1, dc, ic) | codes_rev]
      end

    Enum.reverse(codes)
  end

  defp close_change(i1, j1, dc, 0), do: {:delete, i1, i1 + dc, j1, j1}
  defp close_change(i1, j1, 0, ic), do: {:insert, i1, i1, j1, j1 + ic}
  defp close_change(i1, j1, dc, ic), do: {:replace, i1, i1 + dc, j1, j1 + ic}

  ## unified diff

  defp build_unified(_path, _a, _b, [], _n), do: ""

  defp build_unified(path, a, b, opcodes, n) do
    case grouped_opcodes(opcodes, n) do
      [] ->
        ""

      groups ->
        header = "--- #{path}\n+++ #{path}\n"
        body = Enum.map_join(groups, "", &format_hunk(&1, a, b))
        header <> body
    end
  end

  defp format_hunk(group, a, b) do
    {_, fi1, _fi2, fj1, _fj2} = hd(group)
    {_, _li1, li2, _lj1, lj2} = List.last(group)
    old_range = format_range(fi1, li2)
    new_range = format_range(fj1, lj2)
    lines = Enum.map_join(group, "", &format_opcode_lines(&1, a, b))
    "@@ -#{old_range} +#{new_range} @@\n" <> lines
  end

  defp format_range(start, stop) do
    beginning = start + 1
    length = stop - start

    cond do
      length == 1 -> "#{beginning}"
      length == 0 -> "#{beginning - 1},0"
      true -> "#{beginning},#{length}"
    end
  end

  defp format_opcode_lines({tag, i1, i2, j1, j2}, a, b) do
    eq_lines = if tag == :equal, do: prefixed_lines(a, i1, i2, " "), else: ""
    del_lines = if tag in [:replace, :delete], do: prefixed_lines(a, i1, i2, "-"), else: ""
    ins_lines = if tag in [:replace, :insert], do: prefixed_lines(b, j1, j2, "+"), else: ""
    eq_lines <> del_lines <> ins_lines
  end

  defp prefixed_lines(_list, from, to, _prefix) when from >= to, do: ""

  defp prefixed_lines(list, from, to, prefix) do
    list
    |> Enum.slice(from, to - from)
    |> Enum.map_join("", fn line -> prefix <> line end)
  end

  ## grouped opcodes (hunk splitting with context)

  defp grouped_opcodes(codes, n) do
    codes = trim_opcodes(codes, n)
    nn = n + n

    {groups_rev, current_rev} =
      Enum.reduce(codes, {[], []}, fn code, {groups, current} ->
        case code do
          {:equal, i1, i2, j1, j2} when i2 - i1 > nn ->
            head = {:equal, i1, min(i2, i1 + n), j1, min(j2, j1 + n)}
            tail = {:equal, max(i1, i2 - n), i2, max(j1, j2 - n), j2}
            group = Enum.reverse([head | current])
            {[group | groups], [tail]}

          _ ->
            {groups, [code | current]}
        end
      end)

    groups =
      if current_rev != [] and not single_equal?(current_rev) do
        [Enum.reverse(current_rev) | groups_rev]
      else
        groups_rev
      end

    Enum.reverse(groups)
  end

  defp single_equal?([{:equal, _, _, _, _}]), do: true
  defp single_equal?(_), do: false

  defp trim_opcodes([first | rest] = codes, n) do
    codes =
      case first do
        {:equal, i1, i2, j1, j2} when i2 - i1 > n ->
          [{:equal, max(i1, i2 - n), i2, max(j1, j2 - n), j2} | rest]

        _ ->
          codes
      end

    trim_last_equal(codes, n)
  end

  defp trim_last_equal(codes, n) do
    {last, rest} = List.pop_at(codes, -1)

    case last do
      {:equal, i1, i2, j1, j2} when i2 - i1 > n ->
        rest ++ [{:equal, i1, min(i2, i1 + n), j1, min(j2, j1 + n)}]

      _ ->
        codes
    end
  end

  ## line splitting (LF; upstream edit tool normalizes CRLF/CR to LF)

  defp split_lines(""), do: []

  defp split_lines(text) do
    if String.ends_with?(text, "\n") do
      text |> String.split("\n") |> Enum.drop(-1)
    else
      String.split(text, "\n")
    end
  end

  defp split_keepends(""), do: []

  defp split_keepends(text) do
    if String.ends_with?(text, "\n") do
      text |> String.split("\n") |> Enum.drop(-1) |> Enum.map(&(&1 <> "\n"))
    else
      parts = String.split(text, "\n")
      {last, rest} = List.pop_at(parts, -1)
      Enum.map(rest, &(&1 <> "\n")) ++ [last]
    end
  end
end
